/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package storm.tpb.bolts;

import backtype.storm.tuple.Tuple;
import org.apache.log4j.Logger;
import storm.tpb.tools.Rankings;
import storm.tpb.tools.RankingsBot;

/**
 * This bolt merges incoming {@link storm.tpb.tools.Rankings}.
 * <p/>
 * It can be used to merge intermediate rankings generated by {@link storm.tpb.bolts.IntermediateRankingsBolt} into a final,
 * consolidated ranking. To do so, configure this bolt with a globalGrouping on {@link storm.tpb.bolts.IntermediateRankingsBolt}.
 */
public final class TotalRankingsBotBolt extends AbstractRankerBotBolt {

  private static final long serialVersionUID = -8447525895532302198L;
  private static final Logger LOG = Logger.getLogger(TotalRankingsBotBolt.class);

  public TotalRankingsBotBolt() {
    super();
  }

  public TotalRankingsBotBolt(int topN) {
    super(topN);
  }

  public TotalRankingsBotBolt(int topN, int emitFrequencyInSeconds) {
    super(topN, emitFrequencyInSeconds);
  }

  @Override
  void updateRankingsWithTuple(Tuple tuple) {
    RankingsBot rankingsToBeMerged = (RankingsBot) tuple.getValue(0);
    super.getRankingsBot().updateWith(rankingsToBeMerged);
    super.getRankingsBot().pruneZeroCounts();
  }

  @Override
  Logger getLogger() {
    return LOG;
  }

}
